import { Network, DEFAULT_OPTIONS, DEFAULT_CRITERIA } from '../types/network';

/**
 * Petit réseau de démonstration : un réservoir alimente, via une pompe,
 * un château d'eau et une antenne de distribution avec demandes.
 */
export function sampleNetwork(): Network {
  return {
    meta: {
      name: 'Réseau de démonstration',
      author: '',
      description: 'Exemple : bâche/source + pompe + réservoir + distribution',
      createdAt: new Date().toISOString(),
    },
    options: { ...DEFAULT_OPTIONS },
    criteria: { ...DEFAULT_CRITERIA },
    controls: [],
    curves: {},
    patterns: {
      P1: {
        id: 'P1',
        multipliers: [
          0.6, 0.5, 0.5, 0.6, 0.8, 1.0, 1.3, 1.5, 1.4, 1.2, 1.1, 1.0, 1.0, 1.1, 1.2, 1.3, 1.5, 1.6,
          1.4, 1.2, 1.0, 0.9, 0.8, 0.7,
        ],
      },
    },
    nodes: {
      R1: { id: 'R1', type: 'reservoir', x: 0, y: 300, head: 100, label: 'Source' },
      J1: { id: 'J1', type: 'junction', x: 200, y: 300, elevation: 90, baseDemand: 0 },
      J2: { id: 'J2', type: 'junction', x: 400, y: 300, elevation: 95, baseDemand: 8, pattern: 'P1' },
      J3: { id: 'J3', type: 'junction', x: 600, y: 380, elevation: 93, baseDemand: 6, pattern: 'P1' },
      J4: { id: 'J4', type: 'junction', x: 600, y: 220, elevation: 96, baseDemand: 5, pattern: 'P1' },
      J5: { id: 'J5', type: 'junction', x: 800, y: 300, elevation: 92, baseDemand: 7, pattern: 'P1' },
      T1: {
        id: 'T1',
        type: 'tank',
        x: 400,
        y: 500,
        elevation: 115,
        initLevel: 5,
        minLevel: 0,
        maxLevel: 12,
        diameter: 18,
        label: 'Réservoir',
      },
    },
    links: {
      PU1: {
        id: 'PU1',
        type: 'pump',
        node1: 'R1',
        node2: 'J1',
        mode: 'head',
        designFlow: 40,
        designHead: 45,
        status: 'OPEN',
        speed: 1,
        label: 'Pompe',
      },
      P1: {
        id: 'P1L',
        type: 'pipe',
        node1: 'J1',
        node2: 'J2',
        length: 300,
        diameter: 250,
        roughness: 130,
        minorLoss: 0,
        status: 'OPEN',
      },
      P2: {
        id: 'P2L',
        type: 'pipe',
        node1: 'J2',
        node2: 'J3',
        length: 250,
        diameter: 200,
        roughness: 130,
        minorLoss: 0,
        status: 'OPEN',
      },
      P3: {
        id: 'P3L',
        type: 'pipe',
        node1: 'J2',
        node2: 'J4',
        length: 250,
        diameter: 200,
        roughness: 130,
        minorLoss: 0,
        status: 'OPEN',
      },
      P4: {
        id: 'P4L',
        type: 'pipe',
        node1: 'J3',
        node2: 'J5',
        length: 280,
        diameter: 150,
        roughness: 130,
        minorLoss: 0,
        status: 'OPEN',
      },
      P5: {
        id: 'P5L',
        type: 'pipe',
        node1: 'J4',
        node2: 'J5',
        length: 280,
        diameter: 150,
        roughness: 130,
        minorLoss: 0,
        status: 'OPEN',
      },
      P6: {
        id: 'P6L',
        type: 'pipe',
        node1: 'J2',
        node2: 'T1',
        length: 200,
        diameter: 300,
        roughness: 130,
        minorLoss: 0,
        status: 'OPEN',
      },
    },
  };
}
